baseURL = "https://test2-henna-rho.vercel.app/"
languageCode = "en-us"
title = "Hugo-HT"
theme = "hugo-ht"
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true
# enableGitInfo = true

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Posts"
    url = "/en/posts/"
    weight = 3
[[menu.en]]
    name = "中文"
    url = "/cn/posts/"
    weight = 4
[[menu.en]]  # Added Project section in English menu
    name = "Project"
    url = "/en/project/"
    weight = 5

[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 1
[[menu.cn]]
    name = "日志"
    url = "/cn/posts/"
    weight = 2
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 3
[[menu.cn]]  # Added 项目 (Project) section in Chinese menu
    name = "项目"
    url = "/cn/project/"
    weight = 4

[params]
    description = "Personal website of Your Name"
    homeText = "You just need a Hugo blog from scratch"
    # Please make sure `blogDirNmae` matches the name used in `menu` above:
    blogDirName = "posts"
    # singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "media/hugo-logo.png"
    # Edit by yourself:
    GithubEdit = "https://github.com/deng34/test2/edit/main/content/"
    copyright = "&copy;"
    copyrightYear = "2020-2021"
    # Edit by yourself:
    GithubRepo = "https://github.com/USERNAME/REPONAME"
    # Edit by yourself:
    ContentSource = "https://raw.githubusercontent.com/USERNAME/REPONAME/main/content/" 

[params.logo]
  # Change the logo picture as your prefer:
  url = "media/hugo-logo.png" # you can change it
  width = 50.0
  height = 50.0
  alt = "Hugo-ht"

[params.lang]

    [params.lang.author]
      en = "Zea Mays"
      cn = "于米"

    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"

    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"

    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"

    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100
